### ISSUE TITLE
Version 15.6

### ISSUE THREAD

**Issue by yograjyog** [lixinzhan/PlanQA_Plugin#5]
What changes are required for Eclipse 15.6?

**Comment by lixinzhan** [comment]
I do not have an installation of v15. Not sure what changes there should be
yet. But we are going to have a v15 tbox next month. I will be able to
figure that out soon after that.

**Comment by lixinzhan** [comment]
Code migrated to v15.6, labeled as Release_2.0. A few changes were made. For a general idea about the changes to upgrade from 13.6 to 15.6, a good reference is https://www.carlosjanderson.com/upgrade-your-scripts-from-esapi-13-6-to-15-5/
